// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwnhaqnwvpftpmynojqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3bmhhcW53dnBmdHBteW5vanFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTM4MDcsImV4cCI6MjA1NjM4OTgwN30.YfK8hmd87vf9dVCYF7YR8qMPQB2IhArPSV2uNA-zL8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);